#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BOUNDARY_DOC="docs/release-and-support.md"
ROOT_README="README.md"
DOCS_README="docs/README.md"
ANALYZER_GUIDE="docs/guides/analyzer-coverage.md"
ASYNC_GUIDE="docs/guides/asyncapi-kafka.md"
BRANCH_PROTECTION_DOC=".github/BRANCH_PROTECTION.md"

fail() {
  echo "ERROR: $1" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "${ROOT_DIR}/${path}" ]] || fail "Missing required doc: ${path}"
}

require_contains() {
  local path="$1"
  local needle="$2"
  local label="$3"

  grep -Fq -- "$needle" "${ROOT_DIR}/${path}" || fail "${path} is missing ${label}: ${needle}"
}

for path in \
  "$BOUNDARY_DOC" \
  "$ROOT_README" \
  "$DOCS_README" \
  "$ANALYZER_GUIDE" \
  "$ASYNC_GUIDE" \
  "$BRANCH_PROTECTION_DOC"
do
  require_file "$path"
done

require_contains "$BOUNDARY_DOC" "## Текущая стабильная линия" "required section"
require_contains "$BOUNDARY_DOC" "## Последний стабильный релиз" "required section"
require_contains "$BOUNDARY_DOC" "## Текущее состояние репозитория относительно релиза" "required section"
require_contains "$BOUNDARY_DOC" "## Стабильные поверхности" "required section"
require_contains "$BOUNDARY_DOC" "## Предположения по совместимости" "required section"
require_contains "$BOUNDARY_DOC" "## Ограничения" "required section"
require_contains "$BOUNDARY_DOC" "## Fallback-границы" "required section"
require_contains "$BOUNDARY_DOC" '`v1.0.x`' "stable line wording"
require_contains "$BOUNDARY_DOC" "https://github.com/zuevrs/yanote/releases" "GitHub Releases pointer"
require_contains "$BOUNDARY_DOC" '`gradle.properties`' "workspace version-source reference"
require_contains "$BOUNDARY_DOC" '`0.1.0-SNAPSHOT`' "workspace snapshot marker"
require_contains "$BOUNDARY_DOC" '`yanote --version`' "analyzer version-source reference"
require_contains "$BOUNDARY_DOC" '`yanote-js/package.json`' "source-built analyzer version-source reference"
require_contains "$BOUNDARY_DOC" '`0.0.0`' "analyzer version marker"
require_contains "$BOUNDARY_DOC" "HEAD" "repository-vs-release wording"
require_contains "$BOUNDARY_DOC" '`yanote-core`' "published Java module"
require_contains "$BOUNDARY_DOC" '`yanote-recorder-spring-mvc`' "published Java module"
require_contains "$BOUNDARY_DOC" '`yanote-recorder-spring-kafka`' "published Java module"
require_contains "$BOUNDARY_DOC" '`yanote-test-tags-restassured`' "published Java module"
require_contains "$BOUNDARY_DOC" '`yanote-test-tags-cucumber`' "published Java module"
require_contains "$BOUNDARY_DOC" '`yanote-gradle-plugin`' "published Java module"
require_contains "$BOUNDARY_DOC" '`io.github.zuevrs.yanote.gradle`' "Gradle plugin id"
require_contains "$BOUNDARY_DOC" '`yanoteReport`' "Gradle plugin task name"
require_contains "$BOUNDARY_DOC" '`yanoteCheck`' "Gradle plugin task name"
require_contains "$BOUNDARY_DOC" '`1.0.0`' "report schema version"
require_contains "$BOUNDARY_DOC" "Java 21" "Java compatibility baseline"
require_contains "$BOUNDARY_DOC" 'Node `>=20`' "Node compatibility baseline"
require_contains "$BOUNDARY_DOC" '`.nvmrc` = `22`' "repo/dev Node pin"
require_contains "$BOUNDARY_DOC" "Spring Boot 3.x / Spring MVC" "verified recorder path"
require_contains "$BOUNDARY_DOC" "source-built CLI" "primary analyzer path"
require_contains "$BOUNDARY_DOC" "release asset" "fallback release asset wording"
require_contains "$BOUNDARY_DOC" 'tracked `dist/` поверхность default branch' "no-tracked-dist clause"
require_contains "$BOUNDARY_DOC" 'single-document `http(s)` `--spec`' "remote opt-in wording"
require_contains "$BOUNDARY_DOC" "sanitized provenance" "sanitized provenance wording"
require_contains "$BOUNDARY_DOC" "yanote-validation-artifacts" "HTTP CI artifact bundle wording"
require_contains "$BOUNDARY_DOC" "build-and-test-artifacts" "async CI artifact bundle wording"
require_contains "$BOUNDARY_DOC" "HTTP Security Conformance" "security CLI surface"
require_contains "$BOUNDARY_DOC" "security-semantics.stdout" "security sidecar"
require_contains "$BOUNDARY_DOC" "security-semantics.stderr" "security sidecar"
require_contains "$BOUNDARY_DOC" "security-semantics-yanote-report.json" "security sidecar"
require_contains "$BOUNDARY_DOC" "artifact-manifest.txt" "security provenance note"
require_contains "$BOUNDARY_DOC" "artifact-source-paths.txt" "security provenance note"
require_contains "$BOUNDARY_DOC" "yanote-report.html" "HTTP HTML artifact wording"
require_contains "$BOUNDARY_DOC" "yanote-async-report.html" "async HTML artifact wording"
require_contains "$BOUNDARY_DOC" "bash scripts/ci/verify-m012-s02-security-semantics.sh" "focused security proof command"
require_contains "$BOUNDARY_DOC" "security: []" "security clear wording"
require_contains "$BOUNDARY_DOC" '`{}` optional branch' "security optional wording"
require_contains "$BOUNDARY_DOC" "OR между объектами Security Requirement" "security OR wording"
require_contains "$BOUNDARY_DOC" "AND внутри одного объекта" "security AND wording"
require_contains "$BOUNDARY_DOC" "SEMANTIC_HTTP_MISSING_SECURITY" "missing-security wording"
require_contains "$BOUNDARY_DOC" "SEMANTIC_HTTP_UNAVAILABLE_SECURITY" "unavailable-security wording"
require_contains "$BOUNDARY_DOC" "SEMANTIC_HTTP_UNSUPPORTED_SECURITY" "unsupported-security wording"
require_contains "$BOUNDARY_DOC" "httpSecurityConformance" "security report contract surface"
require_contains "$BOUNDARY_DOC" "security_declared_operations" "security summary token"
require_contains "$BOUNDARY_DOC" "security_observed_operations" "security summary token"
require_contains "$BOUNDARY_DOC" "security_observed_evaluations" "security summary token"
require_contains "$BOUNDARY_DOC" "security_truths" "security summary token"
require_contains "$BOUNDARY_DOC" "coverage.operations/status/parameters/aggregate" "legacy numerator wording"
require_contains "$BOUNDARY_DOC" '`examples`, `links`, `callbacks`, `webhooks`' "deferred broader-object wording"
require_contains "$BOUNDARY_DOC" "combined HTTP+async report surface" "no-combined-surface wording"
require_contains "$BOUNDARY_DOC" "hosted dashboard surface" "no-dashboard wording"
require_contains "$BOUNDARY_DOC" "runtime-selected-async-report.stderr" "async retained artifact wording"
require_contains "$BOUNDARY_DOC" "runtime-selected-yanote-async-report.json" "async retained artifact wording"
require_contains "$BOUNDARY_DOC" "runtime-selected-yanote-async-report.html" "async retained HTML artifact wording"
require_contains "$BOUNDARY_DOC" "schema-failure-yanote-async-report.html" "async retained HTML artifact wording"
require_contains "$BOUNDARY_DOC" "selectionMode=runtime" "async runtime-selection wording"
require_contains "$BOUNDARY_DOC" 'redaction-safe строки `binding support`, `declared semantics`, `runtime semantics`' "async summary semantics wording"
require_contains "$BOUNDARY_DOC" "async-summary.md" "collected async summary artifact wording"
require_contains "$BOUNDARY_DOC" "raw retained-header leakage" "no raw retained-header leakage wording"

require_contains "$ROOT_README" "docs/release-and-support.md" "release/support landing pointer"
require_contains "$ROOT_README" '`v1.0.x`' "root landing stable line"
require_contains "$ROOT_README" "security-semantics.stdout" "root landing security sidecar"
require_contains "$ROOT_README" "coverage.operations/status/parameters/aggregate" "root landing legacy numerator wording"
require_contains "$ROOT_README" "yanote-report.html" "root landing HTTP HTML wording"
require_contains "$ROOT_README" "yanote-validation-artifacts" "root landing HTTP CI bundle wording"
require_contains "$ROOT_README" 'single-document `http(s)` URL поддерживается только как узкий opt-in remote path' "root landing remote wording"
require_contains "$ROOT_README" "combined HTTP+async report surface" "root landing no-combined wording"
require_contains "$ROOT_README" "build-and-test-artifacts" "root landing async CI bundle wording"
require_contains "$ROOT_README" "binding support" "root landing widened async summary wording"
require_contains "$ROOT_README" "declared semantics" "root landing widened async summary wording"
require_contains "$ROOT_README" "runtime semantics" "root landing widened async summary wording"
require_contains "$ROOT_README" "raw retained Kafka headers" "root landing no raw-header wording"
require_contains "$DOCS_README" "release-and-support.md" "release/support landing pointer"
require_contains "$DOCS_README" '`v1.0.x`' "docs landing stable line"
require_contains "$DOCS_README" "security-semantics.*" "docs landing security proof surface"
require_contains "$DOCS_README" "yanote-report.html" "docs landing HTTP HTML wording"
require_contains "$DOCS_README" "yanote-async-report.html" "docs landing async HTML wording"
require_contains "$DOCS_README" "summary.deprecatedOperations" "docs landing deprecated additive wording"
require_contains "$DOCS_README" "yanote-validation-artifacts" "docs landing HTTP CI bundle wording"
require_contains "$DOCS_README" "build-and-test-artifacts" "docs landing async CI bundle wording"
require_contains "$DOCS_README" "binding support" "docs landing widened async summary wording"
require_contains "$DOCS_README" "declared semantics" "docs landing widened async summary wording"
require_contains "$DOCS_README" "runtime semantics" "docs landing widened async summary wording"
require_contains "$ANALYZER_GUIDE" "coverage.operations/status/parameters/aggregate" "analyzer guide legacy numerator wording"
require_contains "$ANALYZER_GUIDE" "SEMANTIC_HTTP_MISSING_SECURITY" "analyzer guide missing-security wording"
require_contains "$ANALYZER_GUIDE" "SEMANTIC_HTTP_UNAVAILABLE_SECURITY" "analyzer guide unavailable-security wording"
require_contains "$ANALYZER_GUIDE" "SEMANTIC_HTTP_UNSUPPORTED_SECURITY" "analyzer guide unsupported-security wording"
require_contains "$ANALYZER_GUIDE" "yanote-report.html" "analyzer guide HTTP HTML wording"
require_contains "$ANALYZER_GUIDE" "yanote-validation-artifacts" "analyzer guide HTTP CI bundle wording"
require_contains "$ANALYZER_GUIDE" 'single-document `http(s)` URL поддерживается только как узкий opt-in remote path' "analyzer guide remote wording"
require_contains "$ANALYZER_GUIDE" "summary.deprecatedOperations" "analyzer guide deprecated additive wording"
require_contains "$ASYNC_GUIDE" "runtime-selected-async-report.stderr" "async guide runtime-selection retained artifact wording"
require_contains "$ASYNC_GUIDE" "runtime-selected-yanote-async-report.json" "async guide runtime-selection retained artifact wording"
require_contains "$ASYNC_GUIDE" "runtime-selected-yanote-async-report.html" "async guide runtime-selection retained HTML wording"
require_contains "$ASYNC_GUIDE" "schema-failure-yanote-async-report.html" "async guide schema-failure retained HTML wording"
require_contains "$ASYNC_GUIDE" "selectionMode=runtime" "async guide runtime-selection proof wording"
require_contains "$ASYNC_GUIDE" "yanote-async-report.html" "async guide HTML wording"
require_contains "$ASYNC_GUIDE" "combined HTTP+async report surface" "async guide no-combined wording"
require_contains "$ASYNC_GUIDE" "hosted dashboard" "async guide no-dashboard wording"
require_contains "$ASYNC_GUIDE" "bindingSupport.summary" "async guide widened binding summary wording"
require_contains "$ASYNC_GUIDE" "declaredSemantics.summary" "async guide widened declared summary wording"
require_contains "$ASYNC_GUIDE" "runtimeSemantics.summary" "async guide widened runtime summary wording"
require_contains "$ASYNC_GUIDE" "async-summary.md" "async guide collected summary artifact wording"
require_contains "$ASYNC_GUIDE" "без публикации raw retained Kafka headers" "async guide no raw-header wording"

require_contains "$BRANCH_PROTECTION_DOC" "build-and-test-artifacts" "branch protection async artifact bundle wording"
require_contains "$BRANCH_PROTECTION_DOC" "GITHUB_STEP_SUMMARY" "branch protection async summary wording"
require_contains "$BRANCH_PROTECTION_DOC" "yanote-async-report.json" "branch protection async report wording"
require_contains "$BRANCH_PROTECTION_DOC" "yanote-async-report.html" "branch protection async HTML wording"
require_contains "$BRANCH_PROTECTION_DOC" "runtime-selected" "branch protection retained companion wording"
require_contains "$BRANCH_PROTECTION_DOC" "schema-failure" "branch protection retained companion wording"
require_contains "$BRANCH_PROTECTION_DOC" "binding support" "branch protection widened async summary wording"
require_contains "$BRANCH_PROTECTION_DOC" "declared semantics" "branch protection widened async summary wording"
require_contains "$BRANCH_PROTECTION_DOC" "runtime semantics" "branch protection widened async summary wording"
require_contains "$BRANCH_PROTECTION_DOC" "raw retained Kafka headers" "branch protection no raw-header wording"

echo "S04 boundary verification passed: release/support surface, additive security proof wording, and deferred broader-object boundary are aligned."